# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  COMMIT_HASH: $(Build.SourceVersion)
  BUILD_DATE: 'dummy'
  VCS_REF: $(Build.SourceVersion)

steps:
- task: Docker@2
  inputs:
    containerRegistry: '6d4f2b4e-1fbf-4ae8-8d3a-c4db5f0b5c0a'
    repository: 'kipters/opencfp'
    command: 'buildAndPush'
    Dockerfile: '.docker/Dockerfile'
    buildContext: '.'
  displayName: 'Build and push Docker image'
